version: '3.8'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
